# Generated by Django 4.0.1 on 2022-12-26 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Docprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Regno', models.IntegerField(blank=True)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('clinic_name', models.CharField(blank=True, max_length=100)),
                ('Addressline1', models.CharField(blank=True, max_length=100)),
                ('Addressline2', models.CharField(blank=True, max_length=100)),
                ('link_of_map', models.CharField(blank=True, max_length=50)),
                ('district', models.CharField(blank=True, max_length=30)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
