# Generated by Django 4.0.1 on 2022-12-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_phone_number_docprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docprofile',
            name='Regno',
        ),
        migrations.AddField(
            model_name='docprofile',
            name='regno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
