# Generated by Django 4.0.1 on 2023-01-02 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_docprofile_regno_docprofile_regno'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('time_start', models.TimeField(blank=True)),
                ('time_end', models.TimeField(blank=True)),
                ('totaltoken', models.IntegerField(blank=True)),
                ('token_booked', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
