# Generated by Django 4.0.1 on 2023-01-15 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_otp_alter_consulttime_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulttime',
            name='doctordetails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.docprofile'),
        ),
        migrations.AlterField(
            model_name='consulttime',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time', to=settings.AUTH_USER_MODEL),
        ),
    ]
