# Generated by Django 4.0.1 on 2023-01-15 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_consulttime_doctordetails_alter_consulttime_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulttime',
            name='doctordetails',
        ),
    ]
