# Generated by Django 4.0.1 on 2023-01-15 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_consulttime_doctordetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulttime',
            name='doctordetails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.docprofile'),
        ),
    ]
