# Generated by Django 4.0.1 on 2023-02-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_account_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, default='userprofile/Basic_Ui_28186_29.jpg', upload_to='userprofile'),
        ),
    ]
