# Generated by Django 4.0.1 on 2023-02-04 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_account_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('patientname', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=20)),
                ('consutime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.consulttime')),
                ('doctordetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.docprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
