# Generated by Django 4.0.1 on 2023-02-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_slotbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulttime',
            name='token_booked',
            field=models.IntegerField(default=1),
        ),
    ]
