# Generated by Django 4.0.1 on 2023-02-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_consulttime_token_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulttime',
            name='token_booked',
            field=models.IntegerField(default=0),
        ),
    ]
