# Generated by Django 4.0.1 on 2023-02-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_razorpaypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpaypayment',
            name='provider_order_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='razorpaypayment',
            name='enddate',
            field=models.DateField(default=0),
        ),
    ]
