# Generated by Django 4.0.1 on 2023-02-24 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_razorpaypayment_provider_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelcetedPakeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('packege', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.packege')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RazorpayPayment',
        ),
    ]
