# Generated by Django 4.0.1 on 2023-02-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_selcetedpakeg_delete_razorpaypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='docprofile',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
