# Generated by Django 4.0.1 on 2023-03-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_selcetedpakeg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='selcetedpakeg',
            name='enddate',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='packege',
            name='packeduration',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='selcetedpakeg',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
