# Generated by Django 4.0.1 on 2023-03-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_selcetedpakeg_enddate_alter_packege_packeduration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docprofile',
            name='slotadd',
            field=models.BooleanField(default=False),
        ),
    ]
