# Generated by Django 4.0.1 on 2023-03-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_docprofile_slotadd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulttime',
            name='time_end',
            field=models.TimeField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='consulttime',
            name='time_start',
            field=models.TimeField(blank=True, max_length=50),
        ),
    ]
