# Generated by Django 4.0.1 on 2023-03-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_consulttime_time_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, default='userprofile/Basic_Ui__28186_29_rsefEQP.jpg', upload_to='userprofile'),
        ),
    ]
