# Generated by Django 4.0.1 on 2023-03-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_account_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packege',
            name='packeduration',
            field=models.IntegerField(),
        ),
    ]
